LoanSystem/Models/HeaderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LoanSystem.Models
{
    public class HeaderModel
    {
        int drpdwnId { get; set; }
        string drpdwnText { get; set; }       
    }
}

LoanSystem/Models/LoanModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LoanSystem.Models
{
    public class LoanModel
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string income { get; set; }
        public string loanAmount { get; set; }
        public string creditStatus { get; set; }       
    }
}

LoanSystem/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoanSystem.Models;

namespace LoanSystem.Controllers
{
    public class LoanController : Controller
    {
        // GET: Loan
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateNewApplicationForm()
        {
            return PartialView("_CreateLoan");
        }
    }
}

LoanSystem/Views/Loan/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@*<h2>ING Mortgages Platform</h2>*@

@using (Html.BeginForm("CreateNewApplicationForm", "Loan",FormMethod.Post))
{
<div style="outline: none;">
    <input type="button" id="create_app_btn" value="Create New Application" name="submit" />
    @Html.Label("Search For Application:")
    @Html.TextBox("searchText")
    @Html.Label("Profile Control:")
    @Html.DropDownList("Status", new List<SelectListItem>

     {
        new SelectListItem{ Text="Credit Assessor", Value = "0" },
        new SelectListItem{ Text="Credit Approver", Value = "1" },
        new SelectListItem{ Text="Lending Manager", Value = "2" }
     })
</div>

    //Html.RenderPartial("~/Views/Shared/_CreateLoan.cshtml");
}

LoanSystem/Views/Shared/_CreateLoan.cshtml
<h1>Loan Application Form(Status:New)</h1>
@Html.Label("First Name:")
@Html.TextBox("txt_firstname")<br/>
@Html.Label("Last Name:")
@Html.TextBox("txt_lastname")<br />
@Html.Label("Address:")
@Html.TextBox("txt_address")<br />
@Html.Label("Applicant Income:")
@Html.TextBox("income")<br />
@Html.Label("Loan Amount:")
@Html.TextBox("txt_loanAmount")<br />
@Html.Label("Credit Status:")
@Html.Label("Not Approved")<br />

LoanSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
   
</head>
<body>
    <h1>ING Mortgages Platform</h1>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>